[package]
name = "cli_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.1.42"
git2 = "0.18.2"
io = "0.0.2"
chrono = "0.4.35"
argparse = "0.2.2"
